# Generated by Django 6.0.6 on 2026-06-12 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='PENDING', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('row_count_clean', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spend_inr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_spend_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('top_merchants', models.JSONField()),
                ('anomaly_count', models.IntegerField()),
                ('narrative', models.TextField()),
                ('risk_level', models.CharField(max_length=255)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_summary', to='flow.job')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('merchant', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('account_id', models.CharField(max_length=255)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True, null=True)),
                ('llm_category', models.CharField(blank=True, max_length=255, null=True)),
                ('llm_raw_response', models.TextField(blank=True, null=True)),
                ('llm_failed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='flow.job')),
            ],
        ),
    ]
