# Generated by Django 6.0.6 on 2026-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsummary',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsummary',
            name='top_merchants',
            field=models.JSONField(default=list),
        ),
    ]
