# Generated by Django 6.0.6 on 2026-09-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_alter_jobsummary_narrative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
